# Contains installations that are needed by DB developers
# =======================================================
# Install packages
- name: "BASE | Installing DB Developer Software"
  become: yes
  apt:
    pkg:
      - mysql-workbench
    state: present
