# Contains installations that are needed on all workstation machine only
# ======================================================================

# Install Easy packages
- name: "Installing Workstation Software"
  become: yes
  apt: pkg={{ item }} state=installed
  with_items:
  - virtualbox
  - shutter
  - vokoscreen
  - gscan2pdf
  - breeze-icon-theme
  - vlc
  - kdenlive
  - gimp

# Create Folders
- name: "Create folder :: Software"
  file: path=/home/{{ user_name }}/Software state=directory owner={{ user_name }} group={{ user_name }}
- name: "Create folder :: GoogleDrive"
  file: path=/home/{{ user_name }}/GoogleDrive state=directory owner={{ user_name }} group={{ user_name }}
- name: "Create folder :: Email"
  file: path=/home/{{ user_name }}/Email state=directory owner={{ user_name }} group={{ user_name }}
- name: "Create folder :: Greg_OfflineData"
  file: path=/home/{{ user_name }}/Greg_OfflineData state=directory owner={{ user_name }} group={{ user_name }}
- name: "Create folder :: Repos"
  file: path=/home/{{ user_name }}/Repos state=directory owner={{ user_name }} group={{ user_name }}

# Google Chrome
# via http://linuxg.net/how-to-install-google-chrome-42-stable-on-the-most-popular-linux-systems-via-the-official-google-repository/
- name: "Ensure Google linux signing key present"
  become: yes
  apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub state=present

- name: "Ensure Google chrome repo present"
  become: yes
  apt_repository:
    repo: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
    filename: google-chrome
    state: present
    update_cache: yes

- name: "Ensure Google chrome present"
  become: yes
  apt:
    name: "google-chrome-stable"
    state: present

# InSync
#- name: "Insync key"
#  become: yes
#  shell: apt-key adv --keyserver keyserver.ubuntu.com --recv-keys ACCAF35C
- name: "Insync key"
  become: yes
  apt_key: keyserver=keyserver.ubuntu.com id=ACCAF35C

- name: "Ensure Insync repo present"
  become: yes
  apt_repository:
    repo: "deb http://apt.insynchq.com/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} non-free contrib "
    filename: insync
    state: present
    update_cache: yes

- name: "Ensure Insync present"
  become: yes
  apt:
    name: "insync"
    state: present

# Zoom
# Download Deb
- name: "Download Zoom DEB"
  get_url:
       url="https://zoom.us/client/latest/zoom_amd64.deb"
       dest="/home/{{ user_name }}/Downloads/zoom_amd64.deb"

# Install zoom
- name: ZOOM -- Install .deb files
  become: yes
  apt: deb="/home/{{ user_name }}/Downloads/zoom_amd64.deb"

# Wine
  # Enable i386 architecture
  # See: https://wiki.winehq.org/Ubuntu
  # https://stackoverflow.com/questions/29842246/how-to-install-x86-architecture-for-java-using-ansible/33377943#33377943
#- name: Enable i386 architecture in dpkg
#  lineinfile:
#    dest: '/var/lib/dpkg/arch'
#    line: '{{ item.arch }}'
#    create: True
#    state: '{{ item.state|d("present") }}'
#  register: wine__register_arch_enabled
#  when: (item.arch in [ 'i386', 'amd64' ])
#  with_items:
#    - arch: 'i386'
#      state: '{{ "present" if (wine__architecture_i386_enabled | bool) else "absent" }}'
#    - arch: '{{ ansible_kernel | regex_replace("^.*-", "") }}'
  # Update Packages
#- name: Update package lists for Wine installation
#  apt:
#    update_cache: True
#  when: (wine__register_arch_enabled|changed)
