# Contains installations that are needed on all workstation machine only
# ======================================================================

# Install Easy packages
- name: "Installing Workstation Software"
  become: yes
  apt: pkg={{ item }} state=installed
  with_items:
  - virtualbox
  - shutter
  - vokoscreen
  - gscan2pdf
  - breeze-icon-theme
  - vlc
  - kdenlive

# Create Folders
- name: "Create folder :: Software"
  file: path=/home/{{ user_name }}/Software state=directory owner={{ user_name }} group={{ user_name }}
- name: "Create folder :: GoogleDrive"
  file: path=/home/{{ user_name }}/GoogleDrive state=directory owner={{ user_name }} group={{ user_name }}
- name: "Create folder :: Email"
  file: path=/home/{{ user_name }}/Email state=directory owner={{ user_name }} group={{ user_name }}
- name: "Create folder :: Greg_OfflineData"
  file: path=/home/{{ user_name }}/Greg_OfflineData state=directory owner={{ user_name }} group={{ user_name }}
- name: "Create folder :: Repos"
  file: path=/home/{{ user_name }}/Repos state=directory owner={{ user_name }} group={{ user_name }}

# apt tasks file for ansible-role-chrome
# via http://linuxg.net/how-to-install-google-chrome-42-stable-on-the-most-popular-linux-systems-via-the-official-google-repository/

- name: "Ensure Google linux signing key present"
  become: yes
  apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub state=present

- name: "Ensure Google chrome repo present"
  become: yes
  apt_repository:
    repo: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
    #filename: "google-chrome"
    state: present
    update_cache: yes

- name: "Ensure Google chrome present"
  become: yes
  apt:
    name: "google-chrome-stable"
    state: present
