# Eclipse
eclipse_enabled: yes
#user: "{{ user_name }}"
#eclipse_owner: "{{ user_name }}"
#eclipse_group: "{{ user_name }}"
#home: "{{ home_folder }}"
eclipse_owner_home: "{{ home_folder }}"
#eclipse_base_dir: "/usr/local/eclipse"
eclipse_base_dir: "{{ home_folder }}/Software/Eclipse"
eclipse_link_base_dir: "/opt"
eclipse_dir_tmp: "/tmp" # or override with "{{ tempdir.stdout }} in order to have be sure to download the file"

#eclipse_name: "kepler" 3.7.2.1
#eclipse_name: "luna" 4.4
#eclipse_name: "mars" 4.5
#eclipse_name: "neon" 4.6
#eclipse_name: "neon"
eclipse_name: "2018-12"
eclipse_release_flag: "R"
eclipse_major: "4"
eclipse_minor: "10"
eclipse_version: "{{eclipse_major}}.{{eclipse_minor}}"

eclipse_archive_extracted: "eclipse"
#modeling
#eclipse_archive: "eclipse-modeling-{{eclipse_name}}-R-linux-gtk-x86_64.tar.gz"
#eclipse_archive: "eclipse-java-{{eclipse_name}}-SR1-linux-gtk-x86_64.tar.gz"
#eclipse_archive: "eclipse-jee-{{eclipse_name}}-SR1-linux-gtk-x86_64.tar.gz"
#eclipse_archive: "eclipse-jee-{{eclipse_name}}-R-linux-gtk-x86_64.tar.gz"
#eclipse_archive: "eclipse-jee-{{eclipse_name}}-3-RC3-linux-gtk-x86_64.tar.gz"
eclipse_archive: "eclipse-jee-2018-12-R-linux-gtk-x86_64.tar.gz"

#eclipse_url: "https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/{{eclipse_name}}/R/{{eclipse_archive}}&r=1"
#eclipse_url: "http://eclipse.mirror.triple-it.nl/technology/epp/downloads/release/{{eclipse_name}}/R/{{eclipse_archive}}"
#eclipse_url: "http://eclipse.mirror.triple-it.nl/technology/epp/downloads/release/{{eclipse_name}}/3.RC3/{{eclipse_archive}}"
eclipse_url: "http://mirror.ufs.ac.za/eclipse/technology/epp/downloads/release/{{eclipse_name}}/{{eclipse_release_flag}}/{{eclipse_archive}}"

#eclipse_home_dir: "{{ eclipse_base_dir }}/{{ eclipse_name }}-{{ eclipse_version }}"
eclipse_home_dir: "{{ eclipse_base_dir }}/{{ eclipse_name }}"
#eclipse_desktop: "/usr/share/applications/eclipse.desktop"
eclipse_desktop: "{{ eclipse_owner_home }}/.local/share/applications/eclipse.desktop"

#eclipse_plugins_enabled: yes                          # Enable plugins
#eclipse_plugins_emf_enabled: no                       # Enable plugins
#eclipse_plugins_cdt_enabled: no                       # Enable plugins
#eclipse_plugins_cmakeed_enabled: no                   # Enable plugins
#eclipse_plugins_openinterminal_enabled: no            # Enable plugins
#eclipse_plugins_protobuf_enabled: no                  # Enable plugins
#eclipse_plugins_yedit_enabled: no                     # Enable plugins
#eclipse_plugins_shelled_enabled: no                   # Enable plugins
#eclipse_plugins_webpageed_enabled: no                 # Enable plugins
#eclipse_plugins_pydev_enabled: no                     # Enable plugins
#eclipse_plugins_m2e_enabled: no                       # Enable plugins

#eclipse_ini_enabled: yes                              # Enable overriding eclipse.ini
##default is 256m
##eclipse_launcher_XXMaxPermSize: "512m"
#eclipse_launcher_XXMaxPermSize: ""
##default is 256m
##eclipse_XXMaxPermSize: "1024m"
#eclipse_XXMaxPermSize: ""
##default is -Xms40m
#eclipse_Xms: "512m"
##default is -Xmx512m
#eclipse_Xmx: "2048m"
