# Containes installations for tools used for Test development
# ===========================================================
# Jmeter
# SOAPUI
# ARC for Chrome


# SoapUI
# Notes:
# To ensure we don't overwrite the previous installation each runtime
# This playbook only extracts the archive file (and does the rest of the installation steps)
# If a new download was needed.

- name: "SOAPUI | Install dependencies"
  become: yes
  apt: name={{ item }} state=latest
  with_items:
    - unzip

- name: "SOAPUI | Create SoapUI Directory"
  become: yes
  file: name={{ soapui_install_dir }}
        state=directory
        owner={{ user_name }}
        group={{ user_name }}

- name: "SOAPUI | Download SoapUI binaries"
  get_url: url=http://smartbearsoftware.com/distrib/soapui/{{ soapui_version }}/SoapUI-{{ soapui_version }}-linux-bin.tar.gz
    dest={{ home_folder }}/Downloads/soapui-{{ soapui_version }}.tar.gz
  register: soapui_download

- name: "SOAPUI | Untar SoapUI"
  when: soapui_download.changed
  unarchive:
    copy=no
    src={{ home_folder }}/Downloads/soapui-{{ soapui_version }}.tar.gz
    dest={{ soapui_install_dir }}

- name: "SOAPUI | Create SoapUI version directory Symlink"
  when: soapui_download.changed
  file:
    src="{{ soapui_install_dir }}/SoapUI-{{ soapui_version }}"
    path="{{ soapui_install_dir }}/latest"
    state=link

- name: "SOAPUI | Extract SoapUI icon from jar"
  when: soapui_download.changed
  command: bash -c 'unzip -p soapui-{{ soapui_version }}.jar com/eviware/soapui/resources/images/favicon.png >./favicon.png'
           chdir={{ soapui_install_dir }}/latest/bin

- name: "SOAPUI | Create symlink in bin folder"
  when: soapui_download.changed
  become: yes
  file:
    src={{ soapui_install_dir }}/latest/bin/soapui.sh
    dest=/usr/bin/soapui
    state=link

  # Note: this simply creates the .desktop file, which can then be found via the launcher and pinned to the dock
- name: "SOAPUI| Configure icon and desktop entry"
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and (soapui_download.changed)
  template: src=templates/soapui.desktop.j2 dest={{ soapui_desktop }} mode=755
  with_items:
    - {
      name: "SoapUI",
      exec: "{{ soapui_install_dir }}/latest/bin/soapui.sh",
      icon: "{{ soapui_install_dir }}/latest/bin/favicon.png",
      comment: "SOAPUI - Installed from Ansible playbook",
      categories: "Development",
      path: "{{ soapui_install_dir }}/latest/bin"
    }
