# winehq
winehq_apt_repo_url: deb https://dl.winehq.org/wine-builds/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release }} main

# Variables required for Balsamiq setups
balsamiq_version: "3.5.16"
balsamiq_version_for_folder: "3_5_16"
balsamiq_base_dir: "{{ home_folder }}/Software/Balsamiq"
balsamiq_archive: "Balsamiq_Mockups_3.5.17_bundled.zip"
balsamiq_url: "https://build_archives.s3.amazonaws.com/obsolete/mockups-desktop/3.5.17/{{balsamiq_archive}}"
balsamiq_owner_home: "{{ home_folder }}"
balsamiq_desktop: "{{ balsamiq_owner_home }}/.local/share/applications/balsamiq.desktop"
