# Containes installations for Eclipse
# ===========================================================

# Notes:
# To ensure we don't overwrite the previous installation each runtime
# This playbook only extracts the archive file (and does the rest of the installation steps)
# If a new download was needed.
#
# Ref: https://github.com/AlbanAndrieu/ansible-eclipse



- name: "ECLIPSE | Check user exists"
  user: name={{ user_name }} state=present

#- name: "ECLIPSE | Check user home directory"
#  stat: path={{ eclipse_owner_home }}
#  register: home_present

#- debug: msg="ECLIPSE | Path exists and is a directory"
#  when: home_present.stat.isdir is defined and home_present.stat.isdir == true

###- name: "ECLIPSE | Create temporary directory"
###  shell: mktemp -d
###  register: eclipse_dir_tmp
###  tags: eclipse_setup
###  changed_when: false

#- name: "ECLIPSE | Set eclipse_home variable"
#  set_fact: eclipse_home={{ eclipse_home_dir }}

#- name: "ECLIPSE | Set eclipse variable"
#  set_fact: eclipse="{{ eclipse_home_dir }}/eclipse"

#- name: "ECLIPSE | Debug variables : eclipse_base_dir"
#  debug: msg="Eclipse base dir is {{ eclipse_base_dir }}"

#- name: "ECLIPSE | Debug variables : eclipse_home"
#  debug: msg="Eclipse home dir is {{ eclipse_home }}"

#- name: "ECLIPSE | Debug variables : eclipse"
#  debug: msg="Eclipse dir is {{ eclipse }}"

#- name: "ECLIPSE | Debug variables : eclipse_url"
#  debug: msg="Eclipse download URL is {{ eclipse_url }}"

- name: "ECLIPSE | Download eclipse if we don't have it"
  connection: local
  get_url: url={{ eclipse_url }} dest={{download_base_folder}}/{{ eclipse_archive }} force=no
  register: eclipse_download

#- name: "ECLIPSE | Debug Eclipse download"
#  debug: msg="ECLIPSE | Eclipse download {{ eclipse_download }}"

- name: "ECLIPSE | Create Eclipse base directory"
  become: true
  file:
    dest="{{ eclipse_base_dir }}"
    state=directory
    owner="{{ user_name }}"
    group="{{ user_name }}"
  #when: eclipse_download.changed
  #tags: eclipse_setup

- name: "ECLIPSE | Create Eclipse home directory"
  become: true
  file:
    dest="{{ eclipse_home_dir }}"
    state=directory
    owner="{{ user_name }}"
    group="{{ user_name }}"

- name: "ECLIPSE | Copy eclipse archive into place"
  when: eclipse_download.changed
  become: true
  copy: src={{download_base_folder}}/{{ eclipse_archive }} dest="{{ eclipse_base_dir }}/{{ eclipse_archive }}" owner="{{ user_name }}" group="{{ user_name }}" mode=644
  #ignore_errors: yes
  #tags: eclipse_setup

- name: "ECLIPSE | Untar Eclipse archive"
  when: eclipse_download.changed
  unarchive:
    copy=no
    src={{ eclipse_base_dir }}/{{ eclipse_archive }}
    dest={{ eclipse_home_dir }}

  # Note: this simply creates the .desktop file, which can then be found via the launcher and pinned to the dock
- name: "ECLIPSE | Configure eclipse desktop entry"
  template: src=../templates/eclipse.desktop.j2 dest={{ eclipse_desktop }}
  #when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and eclipse_download.changed
  ignore_errors: yes
  #tags: eclipse_setup

- name: "ECLIPSE | Create a link to eclipse"
  #when: eclipse_download.changed
  become: yes
  file:
    src="{{ eclipse_home_dir }}/eclipse/eclipse"
    dest=/usr/bin/eclipse
    state=link
    owner="{{ user_name }}"

#- import_tasks: cleanups.yml
# ==============================
# ==============================
# cleanups
# ==============================
# ==============================
#- file: path="{{ item }}" state=absent
#  with_fileglob:
#    - "{{ eclipse_home }}/plugins/org.eclipse.jpt.*"
#    - "{{ eclipse_home }}/features/org.eclipse.jpt.*"
#    - "{{ eclipse_home }}/plugins/*jgit*"
#    - "{{ eclipse_home }}/features/*jgit*"
#    - "{{ eclipse_home }}/plugins/*egit*"
#    - "{{ eclipse_home }}/features/*egit*"
#    # those seems to break some stuff, need more testing...
#    # - "{{ eclipse_home }}/plugins/org.eclipse.pde*"
#    # - "{{ eclipse_home }}/features/org.eclipse.pde*"
#    # - "{{ eclipse_home }}/plugins/*validation*"
#    # - "{{ eclipse_home }}/features/*validation*"
#  ignore_errors: true

#- import_tasks: lombok.yml
# ==============================
# ==============================
# lombok
# ==============================
# ==============================
#
#- get_url: url=http://projectlombok.org/downloads/lombok.jar dest={{ eclipse_home }}/lombok.jar
#  become: yes
#
#- lineinfile: dest={{ eclipse_home }}/eclipse.ini line='-javaagent:{{ eclipse_home }}/lombok.jar'
#  become: yes


#- import_tasks: config.yml
#  when: eclipse_ini_enabled

#- name: eclipse | Install eclipse MoDisco & EMF Facet plugins
#  command: "{{ eclipse }} -nosplash \
#    -application org.eclipse.equinox.p2.director \
#    -destination {{ eclipse_home }} \
#    -repository \
#    http://download.eclipse.org/releases/{{ eclipse_name }}/,\
#    http://download.eclipse.org/tools/orbit/downloads/drops/S20110515001817/repository/,\
#    http://download.eclipse.org/technology/swtbot/helios/dev-build/update-site,\
#    http://eclipse-cs.sf.net/update/,\
#    jar:file:org.eclipse.releng.tools-3.7M7.zip \
#    -installIU \
#    org.eclipse.birt.feature.group,\
#    org.eclipse.mylyn.wikitext_feature.feature.group,\
#    org.eclipse.acceleo.sdk.feature.group,\
#    org.eclipse.m2m.atl.sdk.feature.group,\
#    org.eclipse.emf.cdo.sdk.feature.group,\
#    org.eclipse.emf.ecoretools.sdk.feature.group,\
#    org.eclipse.emf.sdk.feature.group,\
#    org.eclipse.emf.compare.sdk.feature.group,\
#    org.eclipse.emf.query.sdk.feature.group,\
#    org.eclipse.emf.validation.sdk.feature.group,\
#    org.eclipse.jet.sdk.feature.group,\
#    org.eclipse.net4j.sdk.feature.group,\
#    org.eclipse.ocl.all.sdk.feature.group,\
#    org.eclipse.m2m.qvt.oml.sdk.feature.group,\
#    org.eclipse.uml2.sdk.feature.group,\
#    org.antlr.runtime,\
#    org.apache.derby,\
#    org.apache.derby.source,\
#    org.apache.log4j,\
#    org.apache.log4j.source,\
#    org.apache.commons.lang,\
#    org.apache.commons.lang.source,\
#    org.apache.commons.jxpath,\
#    org.apache.commons.jxpath.source,\
#    net.sourceforge.nattable.core,\
#    net.sourceforge.nattable.core.source,\
#    org.prefuse,\
#    org.prefuse.source,\
#    org.eclipse.releng.tools.feature.group,\
#    org.eclipse.swtbot.eclipse.feature.group,\
#    org.eclipse.swtbot.feature.group,\
#    net.sf.eclipsecs.feature.group"
#  when: eclipse_plugins_emf_enabled and eclipse_plugins_enabled

##TODO failed
#- name: eclipse | Install eclipse CDT plugins
#  command: "{{ eclipse }} -nosplash \
#  -application org.eclipse.equinox.p2.director \
#  -destination {{ eclipse_home }} \
#  -repository http://download.eclipse.org/releases/{{ eclipse_name }}/,http://download.eclipse.org/tools/cdt/releases/helios/ \
#  -installIU org.eclipse.cdt.feature.group \
#  -installIU org.eclipse.cdt.sdk.feature.group \
#  -installIU org.eclipse.cdt.platform.feature.group \
#  -installIU org.eclipse.cdt.debug.ui.memory.feature.group \
#  -installIU org.eclipse.cdt.debug.edc.feature.group \
#  -installIU org.eclipse.cdt.util.feature.group"
#  when: eclipse_plugins_cdt_enabled and eclipse_plugins_enabled
#  ignore_errors: true

##cmakeed - CMake editor
#- name: eclipse | Install eclipse CMake editor plugins
#  command: "{{ eclipse }} -nosplash \
#  -application org.eclipse.equinox.p2.director \
#  -destination {{ eclipse_home }} \
#  -repository http://download.eclipse.org/releases/{{ eclipse_name }}/,http://cmakeed.sourceforge.net/eclipse/ \
#  -installIU com.cthing.cmakeed.feature.feature.group"
#  when: eclipse_plugins_cmakeed_enabled and eclipse_plugins_enabled
#  ignore_errors: true

##OpenInTerminal - Add option in context menu
#- name: eclipse | Install eclipse Open In Terminal plugins
#  command: "{{ eclipse }} -nosplash \
#  -application org.eclipse.equinox.p2.director \
#  -destination {{ eclipse_home }} \
#  -repository http://download.eclipse.org/releases/{{ eclipse_name }}/,http://eclipse-openinterminal.googlecode.com/svn/trunk/site/ \
#  -installIU OpenInTerminal.feature.group"
#  when: eclipse_plugins_openinterminal_enabled and eclipse_plugins_enabled
#  ignore_errors: true

##protobuf-dt - Google Protobuffer editor
#- name: eclipse | Install eclipse Proto buffer plugins
#  command: "{{ eclipse }} -nosplash \
#  -application org.eclipse.equinox.p2.director \
#  -destination {{ eclipse_home }} \
#  -repository http://download.eclipse.org/releases/{{ eclipse_name }}/,http://download.eclipse.org/modeling/tmf/xtext/updates/composite/releases/,http://protobuf-dt.googlecode.com/git/update-site \
#  -installIU com.google.eclipse.protobuf.feature.group"
#  when: eclipse_plugins_protobuf_enabled and eclipse_plugins_enabled

##yedit - YAML Editor
#- name: eclipse | Install eclipse YAML Editor plugins
#  command: "{{ eclipse }} -nosplash \
#  -application org.eclipse.equinox.p2.director \
#  -destination {{ eclipse_home }} \
#  -repository http://download.eclipse.org/releases/{{ eclipse_name }}/,http://dadacoalition.org/yedit \
#  -installIU org.dadacoalition.yedit.feature.group"
#  when: eclipse_plugins_yedit_enabled and eclipse_plugins_enabled
#  ignore_errors: true

##shelled - Bash Script Editor
#- name: eclipse | Install eclipse Bash Script Editor plugins
#  command: "{{ eclipse }} -nosplash \
#  -application org.eclipse.equinox.p2.director \
#  -destination {{ eclipse_home }} \
#  -repository http://download.eclipse.org/technology/dltk/updates/,https://sourceforge.net/projects/shelled/files/shelled/update/ \
#  -installIU net.sourceforge.shelled.feature.group"
#  when: eclipse_plugins_shelled_enabled and eclipse_plugins_enabled
#  ignore_errors: true

##Web Page Editor
##- name: eclipse | Install eclipse Web Page Editor plugins
##  command: "{{ eclipse }} -nosplash \
##  -application org.eclipse.equinox.p2.director \
##  -destination {{ eclipse_home }} \
##  -repository http://download.eclipse.org/technology/dltk/updates/,https://sourceforge.net/projects/shelled/files/shelled/update/ \
##  -installIU org.eclipse.jst.webpageeditor.feature.feature.group"
##  when: eclipse_plugins_webpageed_enabled and eclipse_plugins_enabled
##  ignore_errors: true

##Pydev
#- name: "ECLIPSE :: Install python pexpect for adding Pydev certificat (apt)"
#  apt: pkg={{ item }} state=present
#  when: ansible_distribution == 'Debian' and eclipse_plugins_pydev_enabled and eclipse_plugins_enabled
#  with_items:
#    - python-pexpect

#- name: "ECLIPSE :: Transfer eclipse Pydev certificate"
#  copy: src=add_pydev_certificate.py dest={{ eclipse_dir_tmp }} mode=0777 force=yes owner={{ eclipse_owner }} group={{ eclipse_group }}
#  when: eclipse_plugins_pydev_enabled and eclipse_plugins_enabled

#- name: "ECLIPSE :: Add eclipse Pydev certificate"
#  command: python {{ eclipse_dir_tmp }}/add_pydev_certificate.py
#  when: eclipse_plugins_pydev_enabled and eclipse_plugins_enabled

#- name: "ECLIPSE :: Install eclipse Pydev plugins"
#  command: "{{ eclipse }} -nosplash \
#  -application org.eclipse.equinox.p2.director \
#  -destination {{ eclipse_home }} \
#  -repository http://download.eclipse.org/technology/dltk/updates/,http://pydev.org/updates/ \
#  -installIU org.python.pydev.feature.feature.group"
#  when: eclipse_plugins_pydev_enabled and eclipse_plugins_enabled
#  ignore_errors: true

##Maven m2e
#- name: "ECLIPSE :: Install eclipse Maven m2e plugins"
#  command: "{{ eclipse }} -nosplash \
#  -application org.eclipse.equinox.p2.director \
#  -destination {{ eclipse_home }} \
#  -repository http://download.eclipse.org/releases/{{ eclipse_name }}/,http://download.eclipse.org/technology/m2e/releases/1.5/1.5.0.20140606-0033 \
#  -installIU org.eclipse.m2e.feature.feature.group,org.eclipse.m2e.logback.feature.feature.group"
#  when: eclipse_plugins_m2e_enabled and eclipse_plugins_enabled
#  ignore_errors: true

#- import_tasks: features.yml

#- name: "ECLIPSE :: fix permissions eclipse home"
#  file: recurse=yes owner={{ eclipse_owner }} group={{ eclipse_group }} dest={{ eclipse_home }}
#  tags: eclipse_setup
#  become: yes

#- name: "ECLIPSE :: Stat {{ eclipse_home }}"
#  stat: path={{ eclipse_home }}
#  register: eclipse_archive_extracted_present
#  become: yes

#- debug: msg=" ECLIPSE | Path exists and is a directory"
#  when: eclipse_archive_extracted_present.stat.isdir is defined and eclipse_archive_extracted_present.stat.isdir == true

#- fail: msg=" ECLIPSE | Whoops! file ownership has changed"
#  when: eclipse_archive_extracted_present.stat.pw_name != '{{ eclipse_owner }}'

###- name: "ECLIPSE | Cleanup temporary directory"
###  file: name={{ eclipse_dir_tmp.stdout }} state=absent
###  tags: eclipse_setup
###  changed_when: false
###  ignore_errors: "{{ ansible_check_mode }}"
###  become: yes

#- debug: msg=" eclipse | Start eclipse {{ eclipse }}"

# ======================================
# ======================================
# ECLIPSE CONFIGS
# ======================================
# ======================================
#- name:  eclipse | Configure eclipse ini configuration (-Xverify:none)
#  lineinfile: dest={{ eclipse_home }}/eclipse.ini line='-Xverify:none'
#  become: yes
#
#- name:  eclipse | Configure eclipse ini configuration (clean)
#  lineinfile: dest={{ eclipse_home }}/eclipse.ini line='-clean' insertbefore='-startup'
#  become: yes
#
#- name:  eclipse | Configure eclipse ini configuration (Launcher GTK_version 2)
#  replace: dest={{ eclipse_home }}/eclipse.ini regexp='(--launcher\.XXMaxPermSize)\n256m' replace='\1\n{{ eclipse_launcher_XXMaxPermSize }}'
#  when: eclipse_launcher_XXMaxPermSize | length > 0
#  become: yes
#
#- name:  eclipse | Configure eclipse ini configuration (Launcher XXMaxPermSize)
##  lineinfile: regexp="(--launcher\.XXMaxPermSize)\n256m" line='\1\n{{ eclipse_launcher_XXMaxPermSize }}' dest={{ eclipse_home }}/eclipse.ini
#  replace: dest={{ eclipse_home }}/eclipse.ini regexp='(--launcher\.XXMaxPermSize)\n256m' replace='\1\n{{ eclipse_launcher_XXMaxPermSize }}'
#  when: eclipse_launcher_XXMaxPermSize | length > 0
#  become: yes
#
#- name:  eclipse | Configure eclipse ini configuration (XXMaxPermSize)
#  lineinfile: regexp="^-XX:MaxPermSize=256m" line="-XX:MaxPermSize={{ eclipse_XXMaxPermSize }}" dest={{ eclipse_home }}/eclipse.ini
#  when: eclipse_XXMaxPermSize | length > 0
#  become: yes
#
#- name:  eclipse | Configure eclipse ini configuration (Xms)
#  lineinfile: regexp="^-Xms40m" line="-Xms{{ eclipse_Xms }}" dest={{ eclipse_home }}/eclipse.ini
#  when: eclipse_Xms | length > 0
#  become: yes
#
#- name:  eclipse | Configure eclipse ini configuration (Xmx)
#  lineinfile: regexp="^-Xmx512m" line="-Xmx{{ eclipse_Xmx }}" dest={{ eclipse_home }}/eclipse.ini
#  when: eclipse_Xmx | length > 0
#  become: yes
#
##TODO add
##-Djava.net.preferIPv4Stack=true
#
##- lineinfile: dest={{ eclipse_home }}/eclipse.ini line='--launcher.GTK_version\n'


# ======================================
# ======================================
# ECLIPSE FEATURES
# ======================================
# ======================================
#- shell: eclipse -application org.eclipse.equinox.p2.director -noSplash -repository {{ item.repo }} -installIUs {{ item.feature }}
#  with_items:
##EclEmma Java Code Coverage	2.3.3.201602231923	com.mountainminds.eclemma.feature.feature.group	Mountainminds GmbH & Co. KG
#    - { repo: 'http://update.eclemma.org/', feature: 'com.mountainminds.eclemma.feature.feature.group'}
#    - { repo: 'http://download.eclipse.org/technology/m2e/releases/', feature: 'org.eclipse.m2e.feature.feature.group'}
#    - { repo: 'http://download.jboss.org/jbosstools/mars/development/updates/', feature: 'org.jboss.ide.eclipse.as.feature.feature.group'}
#    - { repo: 'http://velo.github.io/maven-formatter-plugin/p2/1.5.0', feature: 'com.marvinformatics.formatter.feature.feature.group'}
#    - { repo: 'http://repo1.maven.org/maven2/.m2e/connectors/m2eclipse-buildhelper/0.15.0/N/0.15.0.201405280027/', feature: 'org.sonatype.m2e.buildhelper.feature.feature.group'}
##    - { repo: 'http://beust.com/eclipse/', feature: 'org.testng.eclipse.feature.group'}
#    - { repo: 'http://download.jboss.org/jbosstools/updates/m2e-extensions/m2e-apt', feature: 'org.jboss.tools.maven.apt.feature.feature.group'}
#    - { repo: 'https://raw.githubusercontent.com/wakatime/eclipse-wakatime/master/update-site/', feature: 'com.wakatime.eclipse.feature.feature.group'}
##    - { repo: 'http://download.eclipse.org/technology/dltk/updates/', feature: 'org.eclipse.jst.webpageeditor.feature.feature.group'}
##TODO install dbeaver https://marketplace.eclipse.org/content/dbeaver
##DBeaver Core	3.8.5	org.jkiss.dbeaver.core.feature.feature.group	Serge Rider
##    - { repo: 'http://dbeaver.jkiss.org/update/latest/', feature: 'org.jkiss.dbeaver.core.feature.feature.group'}
##TODO valgrind http://download.eclipse.org/linuxtools/update
##  Vagrant Tooling	2.2.0.201612072123	org.eclipse.linuxtools.vagrant.feature.feature.group	Eclipse Linux Tools
##    - { repo: 'http://download.eclipse.org/linuxtools/update/', feature: 'org.eclipse.linuxtools.vagrant.feature.feature.group'}
##TODO install Shell Script Editor for Eclipse https://marketplace.eclipse.org/category/free-tagging/shell-script
##  Dynamic Languages Toolkit - ShellEd IDE	5.7.0.201610180416	org.eclipse.dltk.sh.feature.group	Eclipse DLTK
##    - { repo: 'http://download.eclipse.org/technology/dltk/updates/', feature: 'org.eclipse.dltk.sh.feature.group'}
##TODO See https://mcuoneclipse.com/2012/06/25/5-best-eclipse-plugins-1-eclox-with-doxygen-graphviz-and-mscgen/
##http://download.gna.org/eclox/update/
##TODO install groovy compiler
##See https://stackoverflow.com/questions/22875051/eclipse-cant-create-groovy-class-in-4-3-2
##Groovy-Eclipse Feature	2.9.2.xx-201702282040-e46	org.codehaus.groovy.eclipse.feature.feature.group	Codehaus.org
##    - { repo: 'http://dist.springsource.org/snapshot/GRECLIPSE/e4.6', feature: 'org.codehaus.groovy.eclipse.feature.feature.group'}
##TODO sconsolidator
##http://www.sconsolidator.com/update
#  ignore_errors: true
