# Containes installations for tools used for Java development
# ===========================================================
# Install Java developer tools
- name: "Installing Java Developer Software"
  apt: pkg={{ item }} state=installed
  with_items:
  - maven
