# Contains installations that are needed on all machines, including servers etc
# ============================================================================
# Install packages
- name: "Installing Base Software"
  apt: pkg={{ item }} state=installed
  with_items:
  - dnsutils
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common


# Copying files
#- name: "Some copy tasks"
#  copy: src=<source location> dest=<destination>  owner=<owner of file>  group<group for the file>  mode=<permissions eg. 755>
