# Contains installations that are needed on all machines, including servers etc
# ============================================================================

# Install packages
- name: "BASE | Installing Base Software"
  become: yes
  apt:
    pkg:
      - dnsutils
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - tar
      - unzip
      - python
      - python3
      - python3-pip
    state: present
    autoclean: yes

- name: "BASE | Create Base download directory"
  become: true
  file:
    dest="{{ download_base_folder }}"
    state=directory
    owner="{{ user_name }}"
    group="{{ user_name }}"


# Copying files
#- name: "Some copy tasks"
#  copy: src=<source location> dest=<destination>  owner=<owner of file>  group<group for the file>  mode=<permissions eg. 755>
