#!/bin/bash
#
# This script plays around with command line params
#

echo "The command is: " $0
echo "The first parameter is: " $1
echo "The second parameter is: " $2
echo "The relative directory in which the command is running is: " $(dirname $0)
MY_PATH=$(dirname $0)
# Now go up on directory
cd $MY_PATH/..
ls
