# Containes installations for tools used for development across multiple languages
# ================================================================================

# Install Easy packages
- name: "BASE | Installing Base Developer Software"
  become: yes
  apt:
    pkg:
      - nano
      - git
      - glogg
      - retext
      - texlive-full
      - texmaker
      - python-pip
      - python-dev
      - build-essential
      - vagrant
    state: present
    autoclean: yes

# Add Atom repo
- name: "ATOM | Registering Atom Repo"
  become: yes
  apt_repository:
    repo: "ppa:webupd8team/atom"
    state: present

# Install Atom packages
- name: "ATOM | Installing Atom"
  become: yes
  apt:
    pkg:
      - atom
    state: present
    autoclean: yes

# Install sphinx
- name: "SPHINX | Install Sphinx with PIP"
  become: yes
  pip:
    name: Sphinx

# Install Docker
- name: "DOCKER | Installing Docker"
  become: yes
  apt:
    pkg:
      - docker.io
      - docker-compose
    state: present

- name: "DOCKER | Starting docker systemctl"
  become: yes
  shell: systemctl start docker

- name: "DOCKER | Enabling docker systemctl"
  become: yes
  shell: systemctl enable docker

- name: "DOCKER | Add Greg user to docker group (This will require system restart)"
  user:
    name: "gregf"
    append: yes
    groups: docker
  become: true

# To test docker (Requires restart on very first install)
#- name: "Testing docker"
#  shell: docker run hello-world
