# Containes installations for tools used for development across multiple languages
# ================================================================================
# Install packages
- name: "Installing Developer Software"
  become: yes
  apt: pkg={{ item }} state=installed
  with_items:
  - nano
  - git
  - glogg
  - retext
